### ISSUE TITLE
jobs.log notebook paths not updated using export_db.py --replace-email command.

### ISSUE THREAD

**Issue by allistaircota** [Lovelytics/migrate#7]
After a recent cutover, the customer flagged that user emails in notebook paths within job task definitions did not get updated, despite us successfully replacing usernames in other relevant log files using export_db.py's `--replace-email`.
I verified and confirmed the acl_jobs.log file gets updated but the jobs.log file does not. The customer had to manually edit the paths in the UI.

I think replacing user emails in the jobs.log file is a fair expectation since the --replace-email command replaces users' names in the paths of the imported notebooks.

I **do not think** notebook paths should have logic to detect if the notebook resides in the Archive folder of E2, simply because we can't be 100% certain that a notebook will end up in an archive folder, but open to discussions on this.

**Comment by veenaramesh** [comment]
solved with most recent commit
